In [3]:
import pandas as pd
from sqlalchemy import create_engine

In [4]:
file_housing = "Nashville Housing Data.csv"

In [5]:
housing_df = pd.read_csv(file_housing, encoding="ISO-8859-1")

In [6]:
housing_df.columns

Index(['Unnamed: 0', 'Unnamed: 0.1', 'Parcel ID', 'Land Use',
       'Property Address', 'Suite/ Condo   #', 'Property City', 'Sale Date',
       'Sale Price', 'Legal Reference', 'Sold As Vacant',
       'Multiple Parcels Involved in Sale', 'Owner Name', 'Address', 'City',
       'State', 'Acreage', 'Tax District', 'Neighborhood', 'image',
       'Land Value', 'Building Value', 'Total Value', 'Finished Area',
       'Foundation Type', 'Year Built', 'Exterior Wall', 'Grade', 'Bedrooms',
       'Full Bath', 'Half Bath'],
      dtype='object')

In [1]:
parcel = "Nashville Parcel.csv"

In [4]:
parcel_df= pd.read_csv(parcel, encoding="ISO-8859-1")

In [5]:
parcel_df.columns

Index(['Assessment Classification*', 'Assessment Improvement',
       'Assessment Land', 'Assessment Total', 'Assessment Year', 'Baths',
       'Beds2', 'Building Condition', 'Building Condition2', 'Building Grade',
       'Building Grade2', 'Building Type', 'Building Type2', 'Current Owner',
       'Deed Reference', 'Exterior Wall', 'Exterior Wall2', 'Fixtures',
       'Fixtures2', 'Foundation Type', 'Foundation Type2', 'Frame Type',
       'Half Bath', 'Half Bath2', 'Improvement Value', 'Land Area',
       'Land Value', 'Location', 'Mailing Address', 'Map & Parcel',
       'Most Recent Sale Date', 'Most Recent Sale Price', 'Neighborhood',
       'Number of Living Units', 'Roof Cover', 'Rooms', 'Rooms2',
       'Square Footage', 'Square Footage2', 'Story Height', 'Story Height2',
       'Tax District', 'Total Appraisal Value', 'Year Built', 'Year Built2',
       'Zone', 'Parcel ID', 'Land Use', 'Property Address', 'Suite/ Condo   #',
       'Property City', 'Sale Date', 'Sale Price', 'Legal Reference',
       'Sold As Vacant', 'Multiple Parcels Involved in Sale',
       'Assessment Improvement Improved', 'Most Recent Sale Price Improved',
       'Improvement Value Improved', 'Assessment Total Improved',
       'Land Value Improved', 'Assessment Land Improved',
       'Total Appraisal Value Improved', 'Square Footage Improved',
       'Building Type Custom', 'Land Area Acres'],
      dtype='object')

In [10]:
housing_df.rename({"Unnamed: 0":"blank1"}, axis="columns", inplace=True)

In [11]:
housing_df.rename({"Unnamed: 0.1":"blank2"}, axis="columns", inplace=True)

In [12]:
housing_df.columns

Index(['blank1', 'blank2', 'Parcel ID', 'Land Use', 'Property Address',
       'Suite/ Condo   #', 'Property City', 'Sale Date', 'Sale Price',
       'Legal Reference', 'Sold As Vacant',
       'Multiple Parcels Involved in Sale', 'Owner Name', 'Address', 'City',
       'State', 'Acreage', 'Tax District', 'Neighborhood', 'image',
       'Land Value', 'Building Value', 'Total Value', 'Finished Area',
       'Foundation Type', 'Year Built', 'Exterior Wall', 'Grade', 'Bedrooms',
       'Full Bath', 'Half Bath'],
      dtype='object')

In [13]:
pd.set_option('display.max_columns', None)
parcel_df.head()

,Assessment Classification*,Assessment Improvement,Assessment Land,Assessment Total,Assessment Year,Baths,Beds2,Building Condition,Building Condition2,Building Grade,Building Grade2,Building Type,Building Type2,Current Owner,Deed Reference,Exterior Wall,Exterior Wall2,Fixtures,Fixtures2,Foundation Type,Foundation Type2,Frame Type,Half Bath,Half Bath2,Improvement Value,Land Area,Land Value,Location,Mailing Address,Map & Parcel,Most Recent Sale Date,Most Recent Sale Price,Neighborhood,Number of Living Units,Roof Cover,Rooms,Rooms2,Square Footage,Square Footage2,Story Height,Story Height2,Tax District,Total Appraisal Value,Year Built,Year Built2,Zone,Parcel ID,Land Use,Property Address,Suite/ Condo #,Property City,Sale Date,Sale Price,Legal Reference,Sold As Vacant,Multiple Parcels Involved in Sale,Assessment Improvement Improved,Most Recent Sale Price Improved,Improvement Value Improved,Assessment Total Improved,Land Value Improved,Assessment Land Improved,Total Appraisal Value Improved,Square Footage Improved,Building Type Custom,Land Area Acres
0,AG/RES,$0,"$2,655","$2,655",2019.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"THAXTON, JESSE RAY & HELEN F.",20110805-0060547,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,$0,7.60 Acres,"$10,621",0 WHITES CREEK PIKE,"204 SAVANNAH EAST CT SPRINGFIELD, TN 37172",001 00 0 001.00,12/05/2006,"$7,500",6801.0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,GSD,"$10,621",NaN,NaN,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2655.0,7500.0,0.0,2655.0,10621.0,2655.0,10621.0,0.0,NaN,7.60
1,AG/RES,$0,"$4,081","$4,081",2019.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"THAXTON, JESSE R.",00006058-0000985,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,$0,8.90 Acres,"$16,323",8538 WHITES CREEK PIKE,"204 SAVANNAH EAST CT SPRINGFIELD, TN 37172",001 00 0 002.00,05/17/1983,"$12,500",6801.0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,GSD,"$16,323",NaN,NaN,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4081.0,12500.0,0.0,4081.0,16323.0,4081.0,16323.0,0.0,NaN,8.90
2,EXE,$0,$0,$0,2019.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,RIDGETOP NATURAL GAS,00010729-0000778,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,$0,2.90 Acres,$0,1005 HIGHLAND AVE,"P O BOX 650 RIDGETOP, TN 37152",002 00 0 001.00,12/18/1997,"$67,000",6802.0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,GSD,$0,NaN,NaN,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,67000.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,2.90
3,EXE,$0,$0,$0,2019.0,2.0,NaN,Poor,NaN,E,NaN,SINGLE FAM,NaN,RIDGETOP NATURAL GAS,00010729-0000778,FRAME,NaN,5.0,NaN,PIERS,NaN,RESD FRAME,0.0,NaN,"$34,800",0.79 Acres,"$12,300",1003 B HIGHLAND AVE,"P.O. BOX 650 RIDGETOP, TN 37152",002 00 0 001.00 001,12/18/1997,"$67,000",6802.0,1.0,METAL,6.0,NaN,"1,224",NaN,1.0,NaN,RT,"$47,100",1932.0,NaN,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,67000.0,34800.0,0.0,12300.0,0.0,47100.0,1224.0,SINGLE FAM,0.79
4,EXE,$0,$0,$0,2019.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,RIDGETOP NATURAL GAS,00010729-0000778,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,$0,2.11 Acres,"$27,400",1003 C HIGHLAND AVE,"P.O. BOX 650 RIDGETOP, TN 37152",002 00 0 001.00 002,12/18/1997,"$67,000",6802.0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,GSD,"$27,400",NaN,NaN,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,67000.0,0.0,0.0,27400.0,0.0,27400.0,0.0,NaN,2.11

In [14]:
parcel_df.dtypes

Assessment Classification*         object
Assessment Improvement             object
Assessment Land                    object
Assessment Total                   object
Assessment Year                   float64
                                   ...
Assessment Land Improved          float64
Total Appraisal Value Improved    float64
Square Footage Improved           float64
Building Type Custom               object
Land Area Acres                   float64
Length: 66, dtype: object

In [14]:
parcel_df = parcel_df.drop(columns = ['Baths', 'Beds2', 'Building Condition', 'Building Condition2', 'Building Grade', 'Building Grade2', 'Building Type2', 'Exterior Wall', 'Exterior Wall2', 'Fixtures', 'Fixtures2', 'Foundation Type2', 'Frame Type', 'Half Bath', 'Half Bath2', 'Mailing Address', 'Neighborhood', 'Number of Living Units', 'Roof Cover', 'Rooms2', 'Square Footage2', 'Story Height', 'Story Height2', 'Year Built2', 'Parcel ID','Land Use', 'Property Address', 'Suite/ Condo   #', 'Property City', 'Legal Reference', 'Sold As Vacant', 'Multiple Parcels Involved in Sale'])

In [15]:
parcel_df.columns

Index(['Assessment Classification*', 'Assessment Improvement',
       'Assessment Land', 'Assessment Total', 'Assessment Year',
       'Building Type', 'Current Owner', 'Deed Reference', 'Foundation Type',
       'Improvement Value', 'Land Area', 'Land Value', 'Location',
       'Map & Parcel', 'Most Recent Sale Date', 'Most Recent Sale Price',
       'Rooms', 'Square Footage', 'Tax District', 'Total Appraisal Value',
       'Year Built', 'Zone', 'Sale Date', 'Sale Price',
       'Assessment Improvement Improved', 'Most Recent Sale Price Improved',
       'Improvement Value Improved', 'Assessment Total Improved',
       'Land Value Improved', 'Assessment Land Improved',
       'Total Appraisal Value Improved', 'Square Footage Improved',
       'Building Type Custom', 'Land Area Acres'],
      dtype='object')

In [16]:
parcel_df.rename(columns={'Assessment Classification*':'assessment_clarification', 'Assessment Improvement':'assess_improvement','Assessment Land':'assess_land', 'Assessment Total':'assess_total', 'Assessment Year':'assess_year', 'Building Type':'bldgtype', 'Current Owner':'current_owner', 'Deed Reference':'deed_reference', 'Foundation Type':'foundation_type', 'Improvement Value':'improvement_value', 'Land Area':'land_area','Land Value':'land_value', 'Map & Parcel':'map_parcel','Most Recent Sale Date':'most_recent_sale_date','Most Recent Sale Price':'most_recent_sale_price','Square Footage':'sq_footage', 'Tax District':'tax_district', 'Total Appraisal Value':'total_appraisal_value', 'Year Built':'year_built', 'Sale Date':'sale_date','Sale Price':'sale_price', 'Assessment Improvement Improved':'assess_improvement_improved', 'Most Recent Sale Price Improved':'recent_sale_price_improved', 'Improvement Value Improved':'improvement_value_improved', 'Assessment Total Improved':'assess_total_improved', 'Land Value Improved':'land_value_improved', 'Assessment Land Improved':'assess_land_improved','Total Appraisal Value Improved':'total_appraisal_value_improved','Square Footage Improved':'sq_footage_improved','Building Type Custom':'custom_bldg_type','Land Area Acres':'land_area_acres'})

,assessment_clarification,assess_improvement,assess_land,assess_total,assess_year,bldgtype,current_owner,deed_reference,foundation_type,improvement_value,...,assess_improvement_improved,recent_sale_price_improved,improvement_value_improved,assess_total_improved,land_value_improved,assess_land_improved,total_appraisal_value_improved,sq_footage_improved,custom_bldg_type,land_area_acres
0,AG/RES,$0,"$2,655","$2,655",2019.0,NaN,"THAXTON, JESSE RAY & HELEN F.",20110805-0060547,NaN,$0,...,2655.0,7500.0,0.0,2655.0,10621.0,2655.0,10621.0,0.0,NaN,7.60
1,AG/RES,$0,"$4,081","$4,081",2019.0,NaN,"THAXTON, JESSE R.",00006058-0000985,NaN,$0,...,4081.0,12500.0,0.0,4081.0,16323.0,4081.0,16323.0,0.0,NaN,8.90
2,EXE,$0,$0,$0,2019.0,NaN,RIDGETOP NATURAL GAS,00010729-0000778,NaN,$0,...,0.0,67000.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,2.90
3,EXE,$0,$0,$0,2019.0,SINGLE FAM,RIDGETOP NATURAL GAS,00010729-0000778,PIERS,"$34,800",...,0.0,67000.0,34800.0,0.0,12300.0,0.0,47100.0,1224.0,SINGLE FAM,0.79
4,EXE,$0,$0,$0,2019.0,NaN,RIDGETOP NATURAL GAS,00010729-0000778,NaN,$0,...,0.0,67000.0,0.0,0.0,27400.0,0.0,27400.0,0.0,NaN,2.11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
281882,RES,$0,"$20,500","$20,500",2019.0,NaN,"TENNESSEE AVENUE DEVELOPMENT,",20180108-0002371,NaN,$0,...,20500.0,0.0,0.0,20500.0,82000.0,20500.0,82000.0,0.0,NaN,0.00
281883,RES,$0,"$20,500","$20,500",2019.0,NaN,"TENNESSEE AVENUE DEVELOPMENT,",20180108-0002371,NaN,$0,...,20500.0,0.0,0.0,20500.0,82000.0,20500.0,82000.0,0.0,NaN,0.00
281884,RES,$0,"$20,500","$20,500",2019.0,NaN,"TENNESSEE AVENUE DEVELOPMENT,",20180108-0002371,NaN,$0,...,20500.0,0.0,0.0,20500.0,82000.0,20500.0,82000.0,0.0,NaN,0.00
281885,RES,$0,"$20,500","$20,500",2019.0,NaN,"TENNESSEE AVENUE DEVELOPMENT,",20180108-0002371,NaN,$0,...,20500.0,0.0,0.0,20500.0,82000.0,20500.0,82000.0,0.0,NaN,0.00
281886,CA/OS,$0,$0,$0,2019.0,NaN,O.I.C. DEMOSS ROAD HOMES,20180416-0035309,NaN,$0,...,0.0,0.0,0.0,0.0,82000.0,0.0,82000.0,0.0,NaN,1.36

In [17]:
parcel_df.to_csv('Clean_Parcel.csv', index=False)

In [18]:
cleanparcel = "Clean_Parcel.csv"
cleanparcel_df = pd.read_csv(cleanparcel, encoding="ISO-8859-1")

In [37]:
cleanparcel_df.dtypes

Assessment Classification*          object
Assessment Improvement              object
Assessment Land                     object
Assessment Total                    object
Assessment Year                    float64
Building Type                       object
Current Owner                       object
Deed Reference                      object
Foundation Type                     object
Improvement Value                   object
Land Area                           object
Land Value                          object
Location                            object
Map & Parcel                        object
Most Recent Sale Date               object
Most Recent Sale Price              object
Rooms                              float64
Square Footage                      object
Tax District                        object
Total Appraisal Value               object
Year Built                         float64
Zone                               float64
Sale Date                           object
Sale Price                         float64
Assessment Improvement Improved    float64
Most Recent Sale Price Improved    float64
Improvement Value Improved         float64
Assessment Total Improved          float64
Land Value Improved                float64
Assessment Land Improved           float64
Total Appraisal Value Improved     float64
Square Footage Improved            float64
Building Type Custom                object
Land Area Acres                    float64
dtype: object

In [20]:
clean_housing_df = housing_df.drop(columns=['blank1', 'blank2','Suite/ Condo   #', 'Sold As Vacant', 'Multiple Parcels Involved in Sale', 'Owner Name', 'Address', 'City', 'State', 'Neighborhood', 'image', 'Exterior Wall', 'Grade', 'Bedrooms', 'Full Bath', 'Half Bath'])

In [21]:
clean_housing_df.head()

,Parcel ID,Land Use,Property Address,Property City,Sale Date,Sale Price,Legal Reference,Acreage,Tax District,Land Value,Building Value,Total Value,Finished Area,Foundation Type,Year Built
0,105 03 0D 008.00,RESIDENTIAL CONDO,1208 3RD AVE S,NASHVILLE,1/24/2013,132000,20130128-0008725,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,105 11 0 080.00,SINGLE FAMILY,1802 STEWART PL,NASHVILLE,1/11/2013,191500,20130118-0006337,0.17,URBAN SERVICES DISTRICT,32000.0,134400.0,168300.0,1149.00000,PT BSMT,1941.0
2,118 03 0 130.00,SINGLE FAMILY,2761 ROSEDALE PL,NASHVILLE,1/18/2013,202000,20130124-0008033,0.11,CITY OF BERRY HILL,34000.0,157800.0,191800.0,2090.82495,SLAB,2000.0
3,119 01 0 479.00,SINGLE FAMILY,224 PEACHTREE ST,NASHVILLE,1/18/2013,32000,20130128-0008863,0.17,URBAN SERVICES DISTRICT,25000.0,243700.0,268700.0,2145.60001,FULL BSMT,1948.0
4,119 05 0 186.00,SINGLE FAMILY,316 LUTIE ST,NASHVILLE,1/23/2013,102000,20130131-0009929,0.34,URBAN SERVICES DISTRICT,25000.0,138100.0,164800.0,1969.00000,CRAWL,1910.0

In [23]:
clean_housing_df.columns

Index(['Parcel ID', 'Land Use', 'Property Address', 'Property City',
       'Sale Date', 'Sale Price', 'Legal Reference', 'Acreage', 'Tax District',
       'Land Value', 'Building Value', 'Total Value', 'Finished Area',
       'Foundation Type', 'Year Built'],
      dtype='object')

In [27]:
clean_housing_df = clean_housing_df.rename(columns={'Parcel ID':'Parcel_ID','Land Use':'Land_Use', 'Property Address':'Property_address', 'Property City':'Property_City', 'Sale Date':'Sale_Data', 'Sale Price':'Sale_Price', 'Legal Reference':'Legal_Reference', 'Tax District':'Tax_District', 'Land Value':'Land_Value', 'Building Value':'Building_Value', 'Total Value':'Total_Value', 'Finished Area':'Finished_Area', 'Foundation Type':'Foundation_Type', 'Year Built':'Year_Built'})

In [90]:
clean_housing_df.to_csv('Clean_Housing.csv', index=False)

In [91]:
clean_housing_df.dtypes

Parcel ID            object
Land Use             object
Property Address     object
Property City        object
Sale Date            object
Sale Price            int64
Legal Reference      object
Acreage             float64
Tax District         object
Land Value          float64
Building Value      float64
Total Value         float64
Finished Area       float64
Foundation Type      object
Year Built          float64
dtype: object